image: docker:19.03.13

include:
  - project: 'ghsc/hazdev/pipeline-build-template'
    ref: 'master'
    file: 'templates/library.yml'

variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: clone
  IMAGE_NAME: "$CI_PROJECT_NAME:${CI_PIPELINE_ID}"
  SERVER_REGISTRY_IMAGE_NAME: "shakecast/server"
  API_REGISTRY_IMAGE_NAME: "shakecast/api-server"
  TWINE_USERNAME: ${PYPI_USERNAME}
  TWINE_PASSWORD: ${PYPI_PASSWORD}

stages:
  - build
  - test
  - release
  - staging
  - deploy
  - publish

.python-test:
  tags:
    - shakecast-backup
  only:
    - merge_requests
  before_script:
    - cd ${CI_PROJECT_DIR}
    - chmod +x test_env.sh
    - ./test_env.sh

.shakecast-dev:
  tags:
    - shakecast-backup

.release:
  before_script:
    - echo ${CI_COMMIT_REF_NAME} > shakecast/version

.build:
  tags:
    - build
  except:
    - schedules

# BUILD STEPS
build-test-images:
  stage: build
  extends: 
    - .shakecast-dev
    - .dind
  only:
    - merge_requests
  script:
    - docker build -f sc-server.dockerfile . -t shakecast-server:test
    - docker build -f web-server.dockerfile . -t shakecast-web-server:test


# TESTING THE PYTHON APP
app-test:
  stage: test
  image: shakecast/centos
  extends: 
    - .shakecast-dev
    - .python-test
  script:
    - python -m shakecast.tests.bundle

api-test:
  stage: test
  image: shakecast/centos
  extends: 
    - .shakecast-dev
    - .python-test
  script:
    - python -m shakecast.api &
    - sleep 5
    - curl localhost:5000

# RELEASE CONTAINERS
release-dev:
  stage: release
  extends:
    - .dind
    - .release
    - .build
  only:
    - master
  script:
    - docker build -f sc-server.dockerfile . -t $CODE_REGISTRY_IMAGE/$SERVER_REGISTRY_IMAGE_NAME:dev
    - docker build -f web-server.dockerfile . -t $CODE_REGISTRY_IMAGE/$API_REGISTRY_IMAGE_NAME:dev
    - docker push $CODE_REGISTRY_IMAGE/$SERVER_REGISTRY_IMAGE_NAME:dev
    - docker push $CODE_REGISTRY_IMAGE/$API_REGISTRY_IMAGE_NAME:dev
  after_script:
    - docker rmi $CODE_REGISTRY_IMAGE/$SERVER_REGISTRY_IMAGE_NAME:dev
    - docker rmi $CODE_REGISTRY_IMAGE/$API_REGISTRY_IMAGE_NAME:dev

release-prod:
  stage: release
  extends:
    - .dind
    - .release
    - .build
  only:
    - tags
  script:
    - docker build -f sc-server.dockerfile . -t $CODE_REGISTRY_IMAGE/$SERVER_REGISTRY_IMAGE_NAME:latest
    - docker build -f web-server.dockerfile . -t $CODE_REGISTRY_IMAGE/$API_REGISTRY_IMAGE_NAME:latest
    - docker push $CODE_REGISTRY_IMAGE/$SERVER_REGISTRY_IMAGE_NAME:latest
    - docker push $CODE_REGISTRY_IMAGE/$API_REGISTRY_IMAGE_NAME:latest
  after_script:
    - docker rmi $CODE_REGISTRY_IMAGE/$SERVER_REGISTRY_IMAGE_NAME:latest
    - docker rmi $CODE_REGISTRY_IMAGE/$API_REGISTRY_IMAGE_NAME:latest

# STAGING
test-staging:
  stage: staging
  only:
    - master
  when: manual
  extends: 
    - .shakecast-dev
    - .dind
  before_script:
    - docker rm -f shakecast-test || true
    - docker rmi $CODE_REGISTRY_IMAGE/$SERVER_REGISTRY_IMAGE_NAME:dev || true
  script:
    - docker run -d -e SC_DOCKER=0 --name=shakecast-test --network=app-network --entrypoint=python $CODE_REGISTRY_IMAGE/$SERVER_REGISTRY_IMAGE_NAME:dev -m shakecast start

prod-staging:
  stage: staging
  only:
    - tags
  when: manual
  extends: 
    - .shakecast-dev
    - .dind
  before_script:
    - docker rm -f shakecast-prod || true
    - docker rmi $CODE_REGISTRY_IMAGE/$SERVER_REGISTRY_IMAGE_NAME:latest || true
  script:
    - docker run -d -e SC_DOCKER=0 --name=shakecast-prod --network=app-network --entrypoint=python $CODE_REGISTRY_IMAGE/$SERVER_REGISTRY_IMAGE_NAME:latest -m shakecast start

# PUBLISH PACKAGES/CONTAINERS
publish-python:
  stage: publish
  image: shakecast/centos
  extends: .release
  only:
    - tags
  when: manual
  script:
    - python -m pip install --upgrade pip
    - pip install setuptools wheel twine
    - python setup.py bdist_wheel
    - twine upload dist/*
