version: '3'

services:
  sc-server:
    image: usgs/shakecast:latest
    environment:
      SHAKECAST_USER_ID: ${SHAKECAST_USER_ID}
      SC_DOCKER: 1
    expose:
      - "1981"
    networks:
      - sc-network
    volumes:
      - "~/pycast/db:/usr/local/shakecast/shakecast/db"
      - "~/pycast/eq_data:/usr/local/shakecast/shakecast/data"
      - "~/pycast/tmp:/usr/local/shakecast/shakecast/tmp"
      - "~/pycast/conf:/usr/local/shakecast/shakecast/conf"
      - "~/pycast/templates:/usr/local/shakecast/shakecast/templates"
      - "~/pycast/logs:/usr/local/shakecast/shakecast/logs"
      - "~/pycast/local_products:/usr/local/shakecast/shakecast/local_products"
      - "~/pycast/assets:/usr/local/shakecast/shakecast/view/assets"
    restart: unless-stopped

  web-server:
    image: usgs/shakecast:latest
    depends_on:
      - sc-server
    ports:
      - "80:5000"
    environment:
      APP_SERVER: 'false'
      SHAKECAST_SERVER_HOST_NAME: 'sc-server'
      SHAKECAST_WEB_PORT: 5000
      SHAKECAST_USER_ID: ${SHAKECAST_USER_ID}
    networks:
      - sc-network
    volumes:
      - "~/pycast/db:/usr/local/shakecast/shakecast/db"
      - "~/pycast/eq_data:/usr/local/shakecast/shakecast/data"
      - "~/pycast/tmp:/usr/local/shakecast/shakecast/tmp"
      - "~/pycast/conf:/usr/local/shakecast/shakecast/conf"
      - "~/pycast/templates:/usr/local/shakecast/shakecast/templates"
      - "~/pycast/logs:/usr/local/shakecast/shakecast/logs"
      - "~/pycast/local_products:/usr/local/shakecast/shakecast/local_products"
      - "~/pycast/assets:/usr/local/shakecast/shakecast/view/assets"
    restart: unless-stopped

  image-server:
    image: usgs/shakecast-imaging:latest
    networks:
      - sc-network
    volumes:
      - "~/pycast/local_products:/usr/local/shakecast/shakecast/local_products"
    environment:
      SHAKECAST_USER_ID: ${SHAKECAST_USER_ID}
    expose:
      - "5000"
    restart: unless-stopped

networks:
  sc-network:
    driver: bridge
